#!/bin/bash
IS_ARM64=""
currentArch="$(uname -m)"
if [ "$currentArch" == "arm64" ];
then
    echo "architecture: arm64"
    IS_ARM64="_arm64"
else
    echo "architecture: $currentArch"
fi

docker build -t registry.dev.kern.ai/code-kern-ai/refinery-record-ide-env:dev$IS_ARM64 .
