name: 'ACR: Docker Branch Images'

on:
  push:
    branches:
      - "**"
      - "!dev"
    tags-ignore:
      - "**"
    
jobs: 
  call-az-acr-push:
    uses: code-kern-ai/cicd-deployment-scripts/.github/workflows/az_acr_push.yml@dev
    secrets: inherit